FROM python:3.11
  
RUN apt-get update
RUN pip install mlflow
RUN pip install mysqlclient
RUN pip install psycopg2
RUN pip install boto3

RUN mkdir -p /home/mlflow
COPY src/run_server.sh /home/mlflow
COPY my_auth_config.ini /home/mlflow/my_auth_config.ini
WORKDIR /home/mlflow

ENTRYPOINT cd /home/mlflow ; ./run_server.sh 
